stages:
  - build_and_release

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

build_and_release_job:
  stage: build_and_release
  image: ubuntu:latest

  script:
    - apt update -y
    - apt install -y software-properties-common curl
    - add-apt-repository ppa:deadsnakes/ppa -y
    - apt update -y
    - apt install -y python3.12 python3-pip python3.12-venv
    - apt install -y qt6-base-dev qt6-wayland libwayland-dev
    - python3.12 -m venv venv
    - . venv/bin/activate
    - pip install -r requirements.txt
    - pwd && pyside6-uic ui/main.ui -o main/ui_main.py
    - pyinstaller --onefile --name "WifiAnalyser" --windowed --add-data "media/floor_template.svg:./media" --add-data "media/mouse_right_click.png:./media" gui.py
    - curl -sL "https://gitlab.com/api/v4/projects/gitlab-org%2Frelease-cli/releases/permalink/latest/downloads/bin/release-cli-linux-amd64" -o /usr/local/bin/release-cli
    - chmod +x /usr/local/bin/release-cli
    - >
      curl --fail-with-body --header "PRIVATE-TOKEN: $TOKEN"
      --request DELETE "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/releases/release"
      || echo "Release 'release' not found, proceeding."
    - >
      curl --fail-with-body --header "PRIVATE-TOKEN: $TOKEN"
      --request DELETE "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/repository/tags/release"
      || echo "Tag 'release' not found, proceeding."
    - release-cli create --name "Continuous Release" --tag-name "release" --ref "$CI_COMMIT_SHA" --assets-link "{\"name\":\"WifiAnalyser\",\"url\":\"${CI_PROJECT_URL}/-/jobs/${CI_JOB_ID}/artifacts/raw/dist/WifiAnalyser\"}"

  artifacts:
    paths:
      - dist/WifiAnalyser