# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.10.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFormLayout, QFrame,
    QHBoxLayout, QLabel, QLineEdit, QMainWindow,
    QPushButton, QSizePolicy, QStatusBar, QWidget)

from widgets.busy_spinner import BusySpinner
from widgets.clickable_label import ClickableLabel

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1331, 713)
        MainWindow.setMinimumSize(QSize(1326, 670))
        MainWindow.setMaximumSize(QSize(1331, 713))
        icon = QIcon(QIcon.fromTheme(u"network-wireless"))
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.horizontalLayout = QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.sidebar_view = QFormLayout()
        self.sidebar_view.setObjectName(u"sidebar_view")
        self.sidebar_view.setFieldGrowthPolicy(QFormLayout.FieldGrowthPolicy.AllNonFixedFieldsGrow)
        self.building_label = QLabel(self.centralwidget)
        self.building_label.setObjectName(u"building_label")

        self.sidebar_view.setWidget(0, QFormLayout.ItemRole.LabelRole, self.building_label)

        self.building_combo = QComboBox(self.centralwidget)
        self.building_combo.addItem("")
        self.building_combo.addItem("")
        self.building_combo.setObjectName(u"building_combo")

        self.sidebar_view.setWidget(0, QFormLayout.ItemRole.FieldRole, self.building_combo)

        self.floor_label = QLabel(self.centralwidget)
        self.floor_label.setObjectName(u"floor_label")

        self.sidebar_view.setWidget(1, QFormLayout.ItemRole.LabelRole, self.floor_label)

        self.floor_combo = QComboBox(self.centralwidget)
        self.floor_combo.addItem("")
        self.floor_combo.addItem("")
        self.floor_combo.addItem("")
        self.floor_combo.addItem("")
        self.floor_combo.addItem("")
        self.floor_combo.addItem("")
        self.floor_combo.addItem("")
        self.floor_combo.addItem("")
        self.floor_combo.addItem("")
        self.floor_combo.addItem("")
        self.floor_combo.addItem("")
        self.floor_combo.setObjectName(u"floor_combo")

        self.sidebar_view.setWidget(1, QFormLayout.ItemRole.FieldRole, self.floor_combo)

        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)

        self.sidebar_view.setWidget(2, QFormLayout.ItemRole.SpanningRole, self.line)

        self.interface_label = QLabel(self.centralwidget)
        self.interface_label.setObjectName(u"interface_label")

        self.sidebar_view.setWidget(3, QFormLayout.ItemRole.LabelRole, self.interface_label)

        self.interface_combo = QComboBox(self.centralwidget)
        self.interface_combo.setObjectName(u"interface_combo")

        self.sidebar_view.setWidget(3, QFormLayout.ItemRole.FieldRole, self.interface_combo)

        self.ping_target_label = QLabel(self.centralwidget)
        self.ping_target_label.setObjectName(u"ping_target_label")

        self.sidebar_view.setWidget(4, QFormLayout.ItemRole.LabelRole, self.ping_target_label)

        self.ping_target = QLineEdit(self.centralwidget)
        self.ping_target.setObjectName(u"ping_target")

        self.sidebar_view.setWidget(4, QFormLayout.ItemRole.FieldRole, self.ping_target)

        self.iperf_addr_label = QLabel(self.centralwidget)
        self.iperf_addr_label.setObjectName(u"iperf_addr_label")

        self.sidebar_view.setWidget(5, QFormLayout.ItemRole.LabelRole, self.iperf_addr_label)

        self.iperf_addr = QLineEdit(self.centralwidget)
        self.iperf_addr.setObjectName(u"iperf_addr")

        self.sidebar_view.setWidget(5, QFormLayout.ItemRole.FieldRole, self.iperf_addr)

        self.iperf_port_label = QLabel(self.centralwidget)
        self.iperf_port_label.setObjectName(u"iperf_port_label")

        self.sidebar_view.setWidget(6, QFormLayout.ItemRole.LabelRole, self.iperf_port_label)

        self.iperf_port = QLineEdit(self.centralwidget)
        self.iperf_port.setObjectName(u"iperf_port")

        self.sidebar_view.setWidget(6, QFormLayout.ItemRole.FieldRole, self.iperf_port)

        self.mouse_click_graphic = QLabel(self.centralwidget)
        self.mouse_click_graphic.setObjectName(u"mouse_click_graphic")

        self.sidebar_view.setWidget(7, QFormLayout.ItemRole.LabelRole, self.mouse_click_graphic)

        self.ap_label = QLabel(self.centralwidget)
        self.ap_label.setObjectName(u"ap_label")

        self.sidebar_view.setWidget(7, QFormLayout.ItemRole.FieldRole, self.ap_label)


        self.horizontalLayout.addLayout(self.sidebar_view)

        self.vertical_seperator = QFrame(self.centralwidget)
        self.vertical_seperator.setObjectName(u"vertical_seperator")
        self.vertical_seperator.setFrameShape(QFrame.Shape.VLine)
        self.vertical_seperator.setFrameShadow(QFrame.Shadow.Sunken)

        self.horizontalLayout.addWidget(self.vertical_seperator)

        self.floor_view = QWidget(self.centralwidget)
        self.floor_view.setObjectName(u"floor_view")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.floor_view.sizePolicy().hasHeightForWidth())
        self.floor_view.setSizePolicy(sizePolicy)
        self.floor_view.setMinimumSize(QSize(1120, 630))
        self.floor_layout = ClickableLabel(self.floor_view)
        self.floor_layout.setObjectName(u"floor_layout")
        self.floor_layout.setGeometry(QRect(0, 0, 1120, 630))
        sizePolicy.setHeightForWidth(self.floor_layout.sizePolicy().hasHeightForWidth())
        self.floor_layout.setSizePolicy(sizePolicy)
        self.floor_layout.setPixmap(QPixmap(u"../d6863b01/floor_template.png"))
        self.floor_layout.setScaledContents(True)
        self.floor_layout.setTextInteractionFlags(Qt.TextInteractionFlag.NoTextInteraction)
        self.fl11 = QPushButton(self.floor_view)
        self.fl11.setObjectName(u"fl11")
        self.fl11.setGeometry(QRect(213, 113, 91, 58))
        self.fl12 = QPushButton(self.floor_view)
        self.fl12.setObjectName(u"fl12")
        self.fl12.setGeometry(QRect(213, 169, 91, 58))
        self.fl13 = QPushButton(self.floor_view)
        self.fl13.setObjectName(u"fl13")
        self.fl13.setGeometry(QRect(213, 224, 91, 58))
        self.fl21 = QPushButton(self.floor_view)
        self.fl21.setObjectName(u"fl21")
        self.fl21.setGeometry(QRect(305, 113, 91, 58))
        self.fl23 = QPushButton(self.floor_view)
        self.fl23.setObjectName(u"fl23")
        self.fl23.setGeometry(QRect(305, 224, 91, 58))
        self.fl22 = QPushButton(self.floor_view)
        self.fl22.setObjectName(u"fl22")
        self.fl22.setGeometry(QRect(305, 169, 91, 58))
        self.fl42 = QPushButton(self.floor_view)
        self.fl42.setObjectName(u"fl42")
        self.fl42.setGeometry(QRect(489, 169, 91, 58))
        self.fl41 = QPushButton(self.floor_view)
        self.fl41.setObjectName(u"fl41")
        self.fl41.setGeometry(QRect(489, 113, 91, 58))
        self.fl31 = QPushButton(self.floor_view)
        self.fl31.setObjectName(u"fl31")
        self.fl31.setGeometry(QRect(397, 113, 91, 58))
        self.fl33 = QPushButton(self.floor_view)
        self.fl33.setObjectName(u"fl33")
        self.fl33.setGeometry(QRect(397, 224, 91, 58))
        self.fl32 = QPushButton(self.floor_view)
        self.fl32.setObjectName(u"fl32")
        self.fl32.setGeometry(QRect(397, 169, 91, 58))
        self.fl43 = QPushButton(self.floor_view)
        self.fl43.setObjectName(u"fl43")
        self.fl43.setGeometry(QRect(489, 224, 91, 58))
        self.sl33 = QPushButton(self.floor_view)
        self.sl33.setObjectName(u"sl33")
        self.sl33.setGeometry(QRect(777, 224, 91, 58))
        self.sl22 = QPushButton(self.floor_view)
        self.sl22.setObjectName(u"sl22")
        self.sl22.setGeometry(QRect(685, 169, 91, 58))
        self.sl21 = QPushButton(self.floor_view)
        self.sl21.setObjectName(u"sl21")
        self.sl21.setGeometry(QRect(685, 113, 91, 58))
        self.sl32 = QPushButton(self.floor_view)
        self.sl32.setObjectName(u"sl32")
        self.sl32.setGeometry(QRect(777, 169, 91, 58))
        self.sl31 = QPushButton(self.floor_view)
        self.sl31.setObjectName(u"sl31")
        self.sl31.setGeometry(QRect(777, 113, 91, 58))
        self.sl43 = QPushButton(self.floor_view)
        self.sl43.setObjectName(u"sl43")
        self.sl43.setGeometry(QRect(869, 224, 91, 58))
        self.sl11 = QPushButton(self.floor_view)
        self.sl11.setObjectName(u"sl11")
        self.sl11.setGeometry(QRect(593, 113, 91, 58))
        self.sl13 = QPushButton(self.floor_view)
        self.sl13.setObjectName(u"sl13")
        self.sl13.setGeometry(QRect(593, 224, 91, 58))
        self.sl12 = QPushButton(self.floor_view)
        self.sl12.setObjectName(u"sl12")
        self.sl12.setGeometry(QRect(593, 169, 91, 58))
        self.sl23 = QPushButton(self.floor_view)
        self.sl23.setObjectName(u"sl23")
        self.sl23.setGeometry(QRect(685, 224, 91, 58))
        self.sl41 = QPushButton(self.floor_view)
        self.sl41.setObjectName(u"sl41")
        self.sl41.setGeometry(QRect(869, 113, 91, 58))
        self.sl42 = QPushButton(self.floor_view)
        self.sl42.setObjectName(u"sl42")
        self.sl42.setGeometry(QRect(869, 169, 91, 58))
        self.fr31 = QPushButton(self.floor_view)
        self.fr31.setObjectName(u"fr31")
        self.fr31.setGeometry(QRect(397, 460, 91, 58))
        self.fr22 = QPushButton(self.floor_view)
        self.fr22.setObjectName(u"fr22")
        self.fr22.setGeometry(QRect(305, 405, 91, 58))
        self.sr32 = QPushButton(self.floor_view)
        self.sr32.setObjectName(u"sr32")
        self.sr32.setGeometry(QRect(777, 405, 91, 58))
        self.fr23 = QPushButton(self.floor_view)
        self.fr23.setObjectName(u"fr23")
        self.fr23.setGeometry(QRect(305, 349, 91, 58))
        self.fr32 = QPushButton(self.floor_view)
        self.fr32.setObjectName(u"fr32")
        self.fr32.setGeometry(QRect(397, 405, 91, 58))
        self.fr33 = QPushButton(self.floor_view)
        self.fr33.setObjectName(u"fr33")
        self.fr33.setGeometry(QRect(397, 349, 91, 58))
        self.fr41 = QPushButton(self.floor_view)
        self.fr41.setObjectName(u"fr41")
        self.fr41.setGeometry(QRect(489, 460, 91, 58))
        self.sr33 = QPushButton(self.floor_view)
        self.sr33.setObjectName(u"sr33")
        self.sr33.setGeometry(QRect(777, 349, 91, 58))
        self.fr13 = QPushButton(self.floor_view)
        self.fr13.setObjectName(u"fr13")
        self.fr13.setGeometry(QRect(213, 349, 91, 58))
        self.sr21 = QPushButton(self.floor_view)
        self.sr21.setObjectName(u"sr21")
        self.sr21.setGeometry(QRect(685, 460, 91, 58))
        self.fr11 = QPushButton(self.floor_view)
        self.fr11.setObjectName(u"fr11")
        self.fr11.setGeometry(QRect(213, 460, 91, 58))
        self.fr12 = QPushButton(self.floor_view)
        self.fr12.setObjectName(u"fr12")
        self.fr12.setGeometry(QRect(213, 405, 91, 58))
        self.sr11 = QPushButton(self.floor_view)
        self.sr11.setObjectName(u"sr11")
        self.sr11.setGeometry(QRect(593, 460, 91, 58))
        self.sr13 = QPushButton(self.floor_view)
        self.sr13.setObjectName(u"sr13")
        self.sr13.setGeometry(QRect(593, 349, 91, 58))
        self.fr21 = QPushButton(self.floor_view)
        self.fr21.setObjectName(u"fr21")
        self.fr21.setGeometry(QRect(305, 460, 91, 58))
        self.sr23 = QPushButton(self.floor_view)
        self.sr23.setObjectName(u"sr23")
        self.sr23.setGeometry(QRect(685, 349, 91, 58))
        self.sr31 = QPushButton(self.floor_view)
        self.sr31.setObjectName(u"sr31")
        self.sr31.setGeometry(QRect(777, 460, 91, 58))
        self.fr43 = QPushButton(self.floor_view)
        self.fr43.setObjectName(u"fr43")
        self.fr43.setGeometry(QRect(489, 349, 91, 58))
        self.fr42 = QPushButton(self.floor_view)
        self.fr42.setObjectName(u"fr42")
        self.fr42.setGeometry(QRect(489, 405, 91, 58))
        self.sr41 = QPushButton(self.floor_view)
        self.sr41.setObjectName(u"sr41")
        self.sr41.setGeometry(QRect(869, 460, 91, 58))
        self.sr42 = QPushButton(self.floor_view)
        self.sr42.setObjectName(u"sr42")
        self.sr42.setGeometry(QRect(869, 405, 91, 58))
        self.sr12 = QPushButton(self.floor_view)
        self.sr12.setObjectName(u"sr12")
        self.sr12.setGeometry(QRect(593, 405, 91, 58))
        self.sr43 = QPushButton(self.floor_view)
        self.sr43.setObjectName(u"sr43")
        self.sr43.setGeometry(QRect(869, 349, 91, 58))
        self.sr22 = QPushButton(self.floor_view)
        self.sr22.setObjectName(u"sr22")
        self.sr22.setGeometry(QRect(685, 405, 91, 58))
        self.busy_spinner = BusySpinner(self.floor_view)
        self.busy_spinner.setObjectName(u"busy_spinner")
        self.busy_spinner.setGeometry(QRect(1043, 16, 50, 50))

        self.horizontalLayout.addWidget(self.floor_view)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QStatusBar(MainWindow)
        self.statusBar.setObjectName(u"statusBar")
        self.statusBar.setSizeGripEnabled(False)
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"WifiAnalyser", None))
        self.building_label.setText(QCoreApplication.translate("MainWindow", u"Building", None))
        self.building_combo.setItemText(0, QCoreApplication.translate("MainWindow", u"A", None))
        self.building_combo.setItemText(1, QCoreApplication.translate("MainWindow", u"B", None))

        self.building_combo.setPlaceholderText(QCoreApplication.translate("MainWindow", u"A", None))
        self.floor_label.setText(QCoreApplication.translate("MainWindow", u"Floor", None))
        self.floor_combo.setItemText(0, QCoreApplication.translate("MainWindow", u"0", None))
        self.floor_combo.setItemText(1, QCoreApplication.translate("MainWindow", u"1", None))
        self.floor_combo.setItemText(2, QCoreApplication.translate("MainWindow", u"2", None))
        self.floor_combo.setItemText(3, QCoreApplication.translate("MainWindow", u"3", None))
        self.floor_combo.setItemText(4, QCoreApplication.translate("MainWindow", u"4", None))
        self.floor_combo.setItemText(5, QCoreApplication.translate("MainWindow", u"5", None))
        self.floor_combo.setItemText(6, QCoreApplication.translate("MainWindow", u"6", None))
        self.floor_combo.setItemText(7, QCoreApplication.translate("MainWindow", u"7", None))
        self.floor_combo.setItemText(8, QCoreApplication.translate("MainWindow", u"8", None))
        self.floor_combo.setItemText(9, QCoreApplication.translate("MainWindow", u"9", None))
        self.floor_combo.setItemText(10, QCoreApplication.translate("MainWindow", u"10", None))

        self.floor_combo.setPlaceholderText(QCoreApplication.translate("MainWindow", u"1", None))
        self.interface_label.setText(QCoreApplication.translate("MainWindow", u"Interface", None))
        self.interface_combo.setPlaceholderText(QCoreApplication.translate("MainWindow", u"wlp1s0", None))
        self.ping_target_label.setText(QCoreApplication.translate("MainWindow", u"Ping target", None))
        self.iperf_addr_label.setText(QCoreApplication.translate("MainWindow", u"IPerf3 target", None))
        self.iperf_port_label.setText(QCoreApplication.translate("MainWindow", u"IPerf3 port", None))
        self.mouse_click_graphic.setText(QCoreApplication.translate("MainWindow", u"*m_graphic*", None))
        self.ap_label.setText(QCoreApplication.translate("MainWindow", u"Place AP", None))
        self.floor_layout.setText("")
        self.fl11.setText("")
        self.fl12.setText("")
        self.fl13.setText("")
        self.fl21.setText("")
        self.fl23.setText("")
        self.fl22.setText("")
        self.fl42.setText("")
        self.fl41.setText("")
        self.fl31.setText("")
        self.fl33.setText("")
        self.fl32.setText("")
        self.fl43.setText("")
        self.sl33.setText("")
        self.sl22.setText("")
        self.sl21.setText("")
        self.sl32.setText("")
        self.sl31.setText("")
        self.sl43.setText("")
        self.sl11.setText("")
        self.sl13.setText("")
        self.sl12.setText("")
        self.sl23.setText("")
        self.sl41.setText("")
        self.sl42.setText("")
        self.fr31.setText("")
        self.fr22.setText("")
        self.sr32.setText("")
        self.fr23.setText("")
        self.fr32.setText("")
        self.fr33.setText("")
        self.fr41.setText("")
        self.sr33.setText("")
        self.fr13.setText("")
        self.sr21.setText("")
        self.fr11.setText("")
        self.fr12.setText("")
        self.sr11.setText("")
        self.sr13.setText("")
        self.fr21.setText("")
        self.sr23.setText("")
        self.sr31.setText("")
        self.fr43.setText("")
        self.fr42.setText("")
        self.sr41.setText("")
        self.sr42.setText("")
        self.sr12.setText("")
        self.sr43.setText("")
        self.sr22.setText("")
    # retranslateUi

