name: Build App

on:
   push:
    branches: [ "main" ]

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: sudo apt-get install -y qt6-base-dev qt6-wayland libwayland-dev
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12.12'
          spec: 'gui.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'wifianalyser'
          options: --onefile, --name "WifiAnalyser", --windowed, --add-data "media/floor_template.svg:.", --add-data "media/mouse_right_click.png:."
      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: 'Continous Release'
          tag_name: 'release'
          body_path: ''
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      - name: Upload Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/wifianalyser
          asset_name: wifianalyser
          asset_content_type: application/octet-stream
